version="2.0"
watch_list=["md/*.md", "tools/xml-gen/README.md"]
hooks=["shebang", "quarto_attributes", "brei"]

[markers]
open="^(?P<indent>\\s*)```(?P<properties>.*)$"
close="^(?P<indent>\\s*)```\\s*$"

